### ISSUE TITLE
The files are broken?

### ISSUE THREAD

**Issue by jacob-kang** [Jiagengzhu/Shadow-dataset-for-crl#1]
Hi.
I just downloaded your datasets and tried to unzip the files.
But the following errors occured.

Archive:  pointlight.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of pointlight.zip or
        pointlight.zip.zip, and cannot find pointlight.zip.ZIP, period.

It seems that the zip files are broekn.

Thanks.

**Comment by Jiagengzhu** [comment]
Hi Jacob,
Thanks for pointing this out. I have uploaded a new version of the dataset files.
You should be able to download them using the original links:

 [Shadow-Sunlight](https://drive.google.com/file/d/14Vrt6vHffLHDAHAKM9ivJsh_hwuRUKlV/view?usp=sharing)

[Shadow-Pointlight](https://drive.google.com/file/d/1mQqnfJ7jVfSTg1iS4GjCVNWD6DCzYv2P/view?usp=sharing)
